### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by shaun12121** [Hywela/Tab-Postion-Cuztomizer-Modified#1]
Hi

First off thanks for this extension. The one we used before this broke recently and the dev had not updated it since 2015. 

For the URL match there is options for first, last, right, left, but it is missing the option for "chrome default".

E.g., I would like to have set using the radial selection the default tab opening position to be "Right of current tab", but for certain URL(s) I would like to have set using the URL match input their default tab opening position to be "chrome default".

That is my most important feature request but if possible as a second feature request you could also have URL match input for "activate tab after tab closing".

Thank you for your time.

**Comment by Hywela** [comment]
Hi, 

1.2.4 should have some of the features you have requested. If they fit to a T what you want i'm not sure. 

![feature_ss](https://user-images.githubusercontent.com/2254437/76680911-5f5ff480-65ed-11ea-94b6-09ecff10e265.PNG)

Should be available in chrome store as soon as its reviewed. 
//K

**Comment by shaun12121** [comment]
From what I can see in that pic I think you've already done enough to get the functionality I requested. Can't wait to test it out.

Thank you for your work.
-Shaun
