### ISSUE TITLE
activate left/right tab after tab closing doesn't work

### ISSUE THREAD

**Issue by lvmm** [Hywela/Tab-Postion-Cuztomizer-Modified#26]
**Describe the bug**
When activate tab after tab closing is set to left or right, first or last tab is activated instead of left/right one

**To Reproduce**
* set tab opening position to 'always last', activate tab after tab closing to 'left', new tab to 'chrome default'
* open https://github.com/Hywela/Tab-Postion-Cuztomizer-Modified/issues
* middle-click on two links Terms and then Privacy at the bottom of the page to open them in new tabs
* go to the last tab (privacy)
* close it  - the leftmost tab is activated

**Expected behaviour**
tab preceding last (Terms) should've been activated

**Desktop (please complete the following information):**
 - OS: windows 10-64
 - chrome
 - Version 91

**Comment by Hywela** [comment]
Hi, 
Did you experience the issue before Chrome V.91 ? 

After abit research it seems to be a bug with v.91. I'l test some workarounds and see if it fixes the bug. 
https://bugs.chromium.org/p/chromium/issues/detail?id=1213925

Thank you for notifying me of this.

**Comment by lvmm** [comment]
Sorry, can't tell - just installed it, never used it on earlier versions of chrome.

**Comment by Hywela** [comment]
Do you mind checking chrome://settings/help
And see if there is a new update 
Just did the same and updated to version Versjon 91.0.4472.164
Seems to work now. 

I also stopped getting Errors that was caused by https://bugs.chromium.org/p/chromium/issues/detail?id=1213925

**Comment by lvmm** [comment]
It's 91.0.4472.77 and I can't update - work notebook, don't have admin access, updates are handled centrally via SCCM. Looks like I have to wait.

**Comment by lvmm** [comment]
Yes, updating to .146 fixed this - sorry for trouble.
