### ISSUE TITLE
打开标签和的动画问题

### ISSUE THREAD

**Issue by zhj9709** [Hywela/Tab-Postion-Cuztomizer-Modified#27]
**Describe the bug**
设置如下
![image](https://user-images.githubusercontent.com/13991774/127608333-23ebc0d7-efc7-43fa-9f51-b3e9c8de0718.png)
具体如视频中的那样（使用PotPlayer调低播放速度观看会比较明显），当前标签页右侧有其他标签页时，打开新标签页的动画与在最右边打开标签页的动画有点不一样

**To Reproduce**
1. 设置`Tab Opening Position right`为`Right of current tab`
2. 打开一个标签页，确保当前标签页的有标签页
3. 打开新的标签页，观察两次打开标签页的动画

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10/11
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 91

**Smartphone (please complete the following information):**

**Additional context**

https://user-images.githubusercontent.com/13991774/127608933-044adee2-e5d6-4850-ae33-c6cab7e4ed16.mp4

**Comment by Hywela** [comment]
Hi, 

Thank you very much for the feedback, Much appreciated.

Yes the animation is different. It is different because when you open the first tab it uses the normal animation for opening a new tab while the animation after, on the other tabs is because it gets moved into the position "right of current tab".

I would not call it a bug, its how chrome works.

**Comment by zhj9709** [comment]
> Hi,
> 
> Thank you very much for the feedback, Much appreciated.
> 
> Yes the animation is different. It is different because when you open the first tab it uses the normal animation for opening a new tab while the animation after, on the other tabs is because it gets moved into the position "right of current tab".
> 
> I would not call it a bug, its how chrome works.

![image](https://user-images.githubusercontent.com/13991774/127723898-d378ac68-03fd-4e72-b3a2-9e0b60191948.png)
当我的 `Tab Opening Position default` 设置为 `Chrome default` 时，在某个网页中打开链接是在当前标签的右侧，但动画不会像在右侧打开书签一样

https://user-images.githubusercontent.com/13991774/127723933-34b964df-227b-4e96-ad29-82c092e41b32.mp4

**Comment by Hywela** [comment]
Still not sure if there is a issue here or what the issue is. 

9d7d15917dc622465798c9e06f02a7228b8e0fac  most likely solves this.
