### ISSUE TITLE
Wrong tab focused after closing tabs.

### ISSUE THREAD

**Issue by kissglay** [Hywela/Tab-Postion-Cuztomizer-Modified#28]
**Describe the bug**
All settings are default. Only this extension installed.
1st tab get focused after closing several tabs.

There's no such issue on latest "Tab Position Customizer 2".

**To Reproduce**

Plz refer to the attachment!
1, 2, 3 are child tabs opened by 0 (opened by middle clicking links). After closing 0, the focus is given to 1, but after closing 1, 2 briefly get focused before the browser stays on the 1st tab of the current window.
Lots of similar weird behaviors can be triggered because of this bug.

![2021-10-08_14 40 01 551_chrome_tab_position_customizer_-_modified_-_Google_Search](https://user-images.githubusercontent.com/529385/136511045-a5503d1e-48cf-45a9-acb0-5fe68e8c9b83.png)

**Comment by Hywela** [comment]
Commit -> 9d7d15917dc622465798c9e06f02a7228b8e0fac 
Pushed to Google store. Eta a day or so.

**Comment by kissglay** [comment]
Another sequence of operations to reproduce it:

1. From the 2nd tab, Alt+Enter to open the 3rd tab.
2. Switch to the 3rd tab and middle mouse clicks to open whatever other tabs.
3. Close the 3rd tab and focus is now on the 4th tab (now the 3rd tab due to the one just closed).
4. Try middle-clicking a link and open it in the background, but the focus snaps back to the 2nd tab.



![2021-10-13_12 09 43 397](https://user-images.githubusercontent.com/529385/137066403-385ecf03-ea5e-4ff7-9048-326361d0f854.gif)
