### ISSUE TITLE
Wrong tab focus on opening new tab (after closing certain tab) (On 1.3.8)

### ISSUE THREAD

**Issue by kissglay** [Hywela/Tab-Postion-Cuztomizer-Modified#29]
**Describe the bug**
I decide to open a new issue, because it's similar to issue #28 but not exactly same. It doesn't snap back to the very 1st tab of current window, and it's now happening when opening a new tab from a tab whose parent tab (sort of) was just closed.

**To Reproduce**

(On 1.3.8 of the extension) Of course, it's not the only way to trigger the issue but it's relatively concise to explain and reproduce.

The only setting modified is "New Tab -> Not Activated(Background)".
As for the sequence of operations performed, plz refer to the attachment, and is described as follows:

1. From 2nd tab, Alt+Enter to open 3rd tab.
2. Switch to 3rd tab and middle mouse clicks to open whatever other tabs.
3. Close 3rd tab and focus is now on 4th tab (now 3rd tab due to the one just closed).
4. Ctrl+Shift+T (reopen last closed tab)
Now the focus is on 2nd tab, which is the opener of the recovered tab (3rd tab).

**Expected behavior**
Tab focus shouldn't have changed.

**Screenshots**
![2021-10-12_01 37 16 688_chrome_Tab_Position_customizer_modified_-_Options_-_Googl](https://user-images.githubusercontent.com/529385/136832037-bf7f242c-a306-4faa-9f42-acd3262a4d17.png)
![2021-10-12_01 46 44 047](https://user-images.githubusercontent.com/529385/136833453-5144ec07-788e-45e6-a55a-4c8faf192597.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : chrome
 - Version : 94.0.4606.81

**Comment by kissglay** [comment]
Another sequence of operations to reproduce it:

1. From the 2nd tab, Alt+Enter to open the 3rd tab.
2. Switch to the 3rd tab and middle mouse clicks to open whatever other tabs.
3. Close the 3rd tab and focus is now on the 4th tab (now the 3rd tab due to the one just closed).
4. Try middle-clicking a link and open it in the background, but the focus snaps back to the 2nd tab.



![2021-10-13_12 09 43 397](https://user-images.githubusercontent.com/529385/137066403-385ecf03-ea5e-4ff7-9048-326361d0f854.gif)

**Comment by Hywela** [comment]
Hi, Thank for reporting this issue you are experiencing.
Going to look into it during next week.

**Comment by kissglay** [comment]
Came across another case: (In this case, the one closed is not some sort of parent tab)
![2021-10-18_21 46 12 092](https://user-images.githubusercontent.com/529385/137744522-840f8458-bd23-4cb6-bbc2-28df43f88119.gif)

**Comment by kissglay** [comment]
Any progress on resolving this issue?

**Comment by Hywela** [comment]
Been very busy lately so it took some time. But yes the new version I'm testing localy seems to be working fine. 

Unfortunately there are alot of functions and combinations and before i push it to the chrome store I will keep it for testing a week or more.  

I estimate around friday at the earliest.

**Comment by kissglay** [comment]
Take your time and no rush.
