### ISSUE TITLE
1.4.0: New tab as background not working at all.

### ISSUE THREAD

**Issue by kissglay** [Hywela/Tab-Postion-Cuztomizer-Modified#30]
**Describe the bug**
On 1.4.0. If New tab -> Not Activated (background) is selected in options. It's actually not working at all. What's wrong?

**To Reproduce**
![2021-11-15_20 11 40 153_chrome_Tab_Position_customizer_modified_-_Options_-_Googl](https://user-images.githubusercontent.com/529385/141780281-5c4fa04f-d0c6-4617-b715-70d7a68bd28c.png)

Alt + Enter in the address bar or left click on links all open tabs foreground.

**Expected behavior**
Does what is chosen in the option.

**Desktop (please complete the following information):**

 - Browser [chrome]
 - Version [95.0.4638.69]

**Comment by Hywela** [comment]
Yup, Pushed a new update.  Missed something and I dident catch it before i pushed 1.4.0. 
1.4.1 is the newest.
