### ISSUE TITLE
After tab swap, current tab position seems incorrect.

### ISSUE THREAD

**Issue by feafdaes** [Hywela/Tab-Postion-Cuztomizer-Modified#40]
**Describe the bug**
After tab swap, current tab position seems incorrect.

**To Reproduce**
1. Set opening tab position: Right
![002723](https://user-images.githubusercontent.com/110446799/188490544-31f0915b-101c-433e-a8a2-11132592436f.PNG)

2. Close chrome and run it again. Open some tabs.

3. Click 'open in new tab'
![002725](https://user-images.githubusercontent.com/110446799/188490785-fb44b969-6421-4fac-bd5b-098a4be34515.PNG)

4. Swap tab position right after creating new tab. (correct: Drag & drop the tab at background) (incorrect: Click the tab and Drag & drop it) (correct: Move to next tab) (incorrect: Move to 2 tabs away)
![002726](https://user-images.githubusercontent.com/110446799/188491213-9d2e6894-2504-48c9-b6cb-b7a792c96482.PNG)
![002727](https://user-images.githubusercontent.com/110446799/188491218-8b575df8-0839-4045-9118-da20a487b70b.PNG)

5. Click 'open in new tab' right after tab swapping. (incorrect: After clicking other tabs, or after swapping tabs again)
![002728](https://user-images.githubusercontent.com/110446799/188491613-e42780e8-c8cb-4538-8502-364ed85bcbfc.PNG)

5. New tab will appear at incorrect position
![002729](https://user-images.githubusercontent.com/110446799/188491829-8f654a87-276c-43d5-b9da-62507daf38fe.PNG)

**Versions**
Tab Position Customizer - Modified: 1.4.1
Chromium: Version 96.0.4664.93 (Official Build) (64-bit)
OS: Windows 7 64bit

**Comment by Hywela** [comment]
Hi, 
Unfortunately I'm not surprised, I know I fixed a similar issue a while ago with tab movement. Im not sure when I will have the time to go over and look into a eventual fix. But I will add it to my todo list.

Thank you for the bug repport.

**Comment by feafdaes** [comment]
I am glad you know it.
Thank you.

**Comment by KnifeFed** [comment]
Any news on this? This issue shouldn't be closed, should it?

**Comment by TestSubject173** [comment]
Closing tab after dragging & dropping still result in unexpected tab position
