### ISSUE TITLE
[Wont Fix] In activated order

### ISSUE THREAD

**Issue by Hywela** [Hywela/Tab-Postion-Cuztomizer-Modified#6]
On closing tab it jumps true the side tab and shows it quick before moving on to the correct tab. Abit like a sublime message. 

**To Reproduce**
Open 3 tabs. 1-2-3.
Move in order 1,2,3,1,3 close 3 and 2 shows quickly. Dosent happen all the time thou. 

> Looked it over quick, and dont have a solution for it at the this time. Probably happens because it calculates abit before setting it to the last activated tab. Code prob need to be reworked to control callbacks better. Or get the calculation time down.

**Comment by zhj9709** [comment]
https://chrome.google.com/webstore/detail/flst-chrome/ajnianifcggmdojhnmjichjmnjpplcha
This will not have such a problem

**Comment by zhj9709** [comment]
https://chrome.google.com/webstore/detail/flst-chrome/ajnianifcggmdojhnmjichjmnjpplcha
This will not have such a problem

**Comment by Hywela** [comment]
Closing issue, Wont be working on fixing it at this time. If enough annoyance I might reopen it but it's a very minor issue i don't have time for at this time unfortunately.

**Comment by zhj9709** [comment]
May I ask if you can solve this problem when you are free? This is really an annoying problem.

**Comment by Hywela** [comment]
Hi @zhj9709, 

#12 #13 
There is a update of libraries and frameworks going to pre production later today with some ui improvements and optimization. If you want, pm me the email of your google account and I will add you to the Beta test (Usually test it around a week or so before i go live on the store with it). 
#
From pre testing: the issue doesn't seem to appear anymore.

**Comment by zhj9709** [comment]
> Hi @zhj9709,
> 
> #12 #13
> There is a update of libraries and frameworks going to pre production later today with some ui improvements and optimization. If you want, pm me the email of your google account and I will add you to the Beta test (Usually test it around a week or so before i go live on the store with it).
> 
> From pre testing: the issue doesn't seem to appear anymore.

I have sent an email to you.

**Comment by Hywela** [comment]
Hi, I saw. Its currently undergoing review in chrome web store atm. Might take a day or two before its out and can be published to testers. (Dont think they work much during the weekends. Usually have to wait till Monday.

Il give a shoutout when its out.

**Comment by zhj9709** [comment]
I have used the version 1.3.1, but the problem still exists. I have tried many extensions with similar functions, and almost all have the same problem.

**Comment by Hywela** [comment]
HI, I have done my best here but I can not see any solution that will work. I have iterated with alot of different solution without any luck and spent more time than I would like on it. 

I agree it can be annoying.  I am sorry to say that this issue will go back as "wont fix". But thank you for the help testing and interest.

**Comment by zhj9709** [comment]
最近好像很少出现这种情况了
