### ISSUE TITLE
tab options for bookmarks

### ISSUE THREAD

**Issue by lazymonkey2** [Hywela/Tab-Postion-Cuztomizer-Modified#7]
Hi, your extension is really good for tab handling, so thanks for your work! :-)
May I suggest a feature: I'd like to set tab options for web sites opened from bookmarks (when browsing I want to open links to the right of current one, but when opening from bookmarks I'd like to open as always right). Is it possibile?
Thanks.

**Comment by Hywela** [comment]
Hi Tortino, 

Sorry for the late answer. 

Did some quick research here and unfortunately there is no api support i could find that would make this easily possible. 

When opening a tab from a bookmark chrome uses the same api for opening the tab, the api in question and callback function does not as I can find include information that it came from "bookmarks" or any other route. 

Thank you for the feedback and the idea, il keep it in mind if something changes in the api changes to make this possible. 

What you can do thou, is have a slight change in the url opening, if it's possible. 
on the bookmark you could type in  nytimes.com/# to open right (change the bookmark url to include the /#
and https://www.nytimes.com/ to open left.

But it kind of need to be in the the order bookmark last with the /# in the list so without it first. Like in the image below. 

![image](https://user-images.githubusercontent.com/2254437/81848074-d87bb980-9554-11ea-9369-65160a71e8fa.png)

Depends abit on if the site in question can handle it thou. 

Wish you all the best, and thanks again for the guestion and feedback. 
// Kristoffer

**Comment by Hywela** [comment]
Closing this issue. Don't hesitate to reopen if you want to add something.
